[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "dataset-utils"
description = "Data and dataset utilities"
version = "0.1.0"
requires-python = ">=3.8,<3.13"
dependencies = ["Pillow"]
readme = "README.md"

[project.urls]
Repository = "https://github.com/prumos/dataset-utils"
Issues = "https://github.com/prumos/dataset-utils/issues"

[project.optional-dependencies]
label-studio = ["label-studio"]

[project.scripts]
gen-tasks = "dataset_utils.scripts.label_studio.gen_tasks:_run"


[tool.setuptools.packages.find]
where = ["src"]
